repositoryUrl: "https://github.com/budivoy/pycookiex.git"

branches:
  - devel

tagFormat: "v${version}"

plugins:
# Determine release type based on commit message tags
- - "@semantic-release/commit-analyzer"
  - preset: conventionalcommits
# Replace
# - pyproject.toml: version with next release version
- - "semantic-release-replace-plugin"
  - replacements:
    - files:
      - pyproject.toml
      from:
        - "^version = \".*\"$"
      to:
        - "version = \"${nextRelease.version}\""
      results:
      - file: pyproject.toml
        hasChanged: true
        numMatches: 1
        numReplacements: 1
      countMatches: true
# Commit replacements
- - "@semantic-release/git"
  - assets:
    - pyproject.toml
    - CHANGELOG.md
    message: "chore(release): ${nextRelease.version}"
# Publish release to GitHub
- - "@semantic-release/github"
  - successComment: false
    failComment: false
    failTitle: false
    labels: false

# Change Unreleased section to new version, and extract release notes from CHANGELOG.md
# The reason of such workaround is to simplify workflow. Release after every PR is inconvenient,
# so this configuration assumes that release triggered manually.
generateNotes:
- - "@semantic-release/exec"
  - generateNotesCmd: "kacl-cli release ${nextRelease.version} -m && kacl-cli get ${nextRelease.version}"
