[tool.poetry]
name = "pycookiex"
version = "0.1.0"
description = "Yet another Python cookiecutter"
authors = ["budivoy"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.2"
pytest-cookies = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
