[tool.poetry]
name = "pycookiex"
version = "0.1.0"
description = "Yet another Python cookiecutter"
authors = ["budivoy"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
