version: '3'

tasks:
  install:
    cmds:
      - poetry install

  lint:
    cmds:
      - poetry run ruff check --config pyproject.toml

  format:
    cmds:
      - poetry run ruff format --config pyproject.toml

  checker:
    cmds:
      - poetry run mypy . --config pyproject.toml

  docs:
    cmds:
      - poetry run mkdocs build --strict --config-file docs/mkdocs.yml

  clean-docs:
    cmds:
      - rm -rf docs/site

  clean:
    cmds:
      - clean-docs
