version: '3'

tasks:
  install:
    cmds:
      - uv install

  test:
    cmds:
      - uv run pytest

  lint:
    cmds:
      - uv run ruff check --config pyproject.toml

  format:
    cmds:
      - uv run ruff format --config pyproject.toml

  checker:
    cmds:
      - uv run mypy . --config pyproject.toml

  docs:
    cmds:
      - uv run mkdocs build --strict --config-file docs/mkdocs.yml

  clean-docs:
    cmds:
      - rm -rf docs/site

  clean:
    cmds:
      - clean-docs
