name: 🤗 Pre-Flight Checks

on:
  pull_request:
  push:
    branches:
      - devel

jobs:
  linters:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ matrix.python-version}}

      - name: Run ruff
        run: |
          poetry run ruff check

      - name: Run mypy
        run: |
          poetry run mypy . --config pyproject.toml

  formatters:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ matrix.python-version}}

      - name: Run format
        run: |
          poetry run ruff format

  pre-commit:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ matrix.python-version}}

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit
        run: |
          poetry run pre-commit run -a

  docs-build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ matrix.python-version}}

      - name: Build docs
        run: |
          poetry run mkdocs build -f --strict --config-file docs/mkdocs.yml
