name: 🤗 Pre-Flight Checks

on:
  pull_request:
  push:
    branches:
      - devel

jobs:
  linters:
    permissions:
      contents: read

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.13']

    runs-on: {{ '${{ matrix.os }}' }}

    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: {{ '${{ matrix.python-version}}' }}

      - name: Run ruff
        run: |
          task lint
{%- if cookiecutter.include_mypy == "yes" %}

      - name: Run mypy
        run: |
          task checker
{%- endif %}

  formatters:
    permissions:
      contents: read

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.13']

    runs-on: {{ '${{ matrix.os }}' }}

    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: {{ '${{ matrix.python-version}}' }}

      - name: Run format
        run: |
          task format

  pre-commit:
    permissions:
      contents: read

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.13']

    runs-on: {{ '${{ matrix.os }}' }}

    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: {{ '${{ matrix.python-version}}' }}

      - name: Install pre-commit
        run: |
          uv pip install pre-commit

      - name: Run pre-commit
        run: |
          uv run pre-commit run -a

  docs-build:
    permissions:
      contents: read

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.13']

    runs-on: {{ '${{ matrix.os }}' }}

    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: {{ '${{ matrix.python-version}}' }}

      - name: Build docs
        run: |
          task docs
