name: 🛠️ Setup Environment
description: A composite action to set up Python with uv and install dependencies.
runs:
  using: "composite"
  steps:

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: |
        uv python install ${{ inputs.python-version }}

    - name: Install Python Dependencies
      run: |
        uv lock
      shell: bash

    - name: Intall Task
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
        echo "~/local/bin/" >> $GITHUB_PATH
      shell: bash

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.12'
