version: '3'

tasks:
  install:
    cmds:
      - uv sync

  test:
    cmds:
      - uv run pytest

  lint:
    cmds:
      - uv run ruff check --config pyproject.toml

  format:
    cmds:
      - uv run ruff format --config pyproject.toml
{%- if cookiecutter.include_mypy == "yes" %}

  checker:
    cmds:
      - uv run mypy . --config pyproject.toml
{%- endif %}

  docs:
    cmds:
      - uv run mkdocs build --strict --config-file docs/mkdocs.yml

  clean-lint:
    cmds:
      - rm -rf .ruff_cache
{%- if cookiecutter.include_mypy == "yes" %}

  clean-checker:
    cmds:
      - rm -rf .mypy_cache
{%- endif %}

  clean-docs:
    cmds:
      - rm -rf docs/site

  clean:
    deps: [clean-lint, clean-checker, clean-docs]
