# Project information
site_name: pycookiex
site_description: Yet another Python cookiecutter 🐍 🍪
site_author: budivoy
site_url: https://budivoy.github.io/pycookiex/
copyright: 'Copyright &copy; budivoy 2024-present'

# Repository
repo_name: pycookiex
repo_url: https://github.com/budivoy/pycookiex

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Intruduction: README.md
  - Examples:
    - Docstring Example: examples/docstring_example.md
  - Other:
    - License: LICENSE.md
    - Changelog: CHANGELOG.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences

hooks:
  - hooks.py

extra:
  md_file_to_update_links:
    - README.md
    - LICENSE.md
    - CHANGELOG.md
  version:
    provider: mike
    alias: true

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]
          import:
            - https://docs.python.org/3/objects.inv
          options:
            # For more options see: https://mkdocstrings.github.io/python/usage/
            docstring_style: google
            show_signature_annotations: true
            show_source: true
            show_submodules: true
            signature_crossrefs: true
            show_symbol_type_toc: true
            separate_signature: false
