site_name: pycookiex
repo_url: https://github.com/budivoy/pycookiex

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Intruduction: README.md
  - Examples:
    - Docstring Example: examples/docstring_example.md
  - Other:
    - License: LICENSE.md
    - Changelog: CHANGELOG.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

hooks:
  - hooks.py

extra:
  md_file_to_update_links:
    - README.md
    - LICENSE.md
    - CHANGELOG.md

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_signature_annotations: true
            show_source: true
            show_submodules: true
