name: Pre-Flight Checks 🤗

on:
  pull_request:
  push:
    branches:
      - devel

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry' # caching poetry dependencies
      - name: Install dependencies
        run: |
          poetry install
      - name: Run ruff
        run: |
          poetry run ruff check
      - name: Run format
        run: |
          poetry run ruff format
