name: 🤗 Pre-Flight Checks

on:
  pull_request:
  push:
    branches:
      - devel

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: '3.12'

      - name: Run ruff
        run: |
          poetry run ruff check

  formatters:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: '3.12'

      - name: Run format
        run: |
          poetry run ruff format
