name: 🤗 Pre-Flight Checks

on:
  pull_request:
  push:
    branches:
      - devel

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: '3.12'

      - name: Run ruff
        run: |
          poetry run ruff check

      - name: Run mypy
        run: |
          poetry run mypy . --config pyproject.toml

  formatters:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: '3.12'

      - name: Run format
        run: |
          poetry run ruff format

  pre-commit:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit
        run: |
          poetry run pre-commit run -a

  docs-build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: '3.12'

      - name: Build docs
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd)/examples
          export PYTHONPATH
          poetry run mkdocs build -f --strict --config-file docs/mkdocs.yml
