name: 📦 Manual Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
        contents: write # to be able to publish a GitHub release
        issues: write # to be able to comment on released issues
        pull-requests: write # to be able to comment on released pull requests

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install semantic-release and plugins
        run: |
          npm install -g semantic-release
          npm install -g @semantic-release/exec
          npm install -g @semantic-release/git
          npm install -g conventional-changelog-conventionalcommits
          npm install -g semantic-release-replace-plugin

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug --dry-run

  publish-docs:
    runs-on: ubuntu-latest

    needs: release

    permissions:
        contents: write # to be able to publish GitHub pages

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          python-version: '3.12'

      - name: Get package version
        run: |
          version="$(poetry version --short)"
          echo "Package version: $version"
          echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV

      - name: Setup git user
        run: |
          git config --global user.name budivoy
          git config --global user.email 1615976+budivoy@users.noreply.github.com

      - name: Deploy documentation to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run mike deploy --push --ignore-remote-status --update-aliases "${{ env.PACKAGE_VERSION }}" latest --config-file docs/mkdocs.yml
